// Action for Functional State
export const ADD_TODO_ITEM = 'ADD_TODO_ITEM'
export const DELETE_TODO_ITEM = 'DELETE_TODO_ITEM'
export const UPDATE_TODO_ITEM = 'UPDATE_TODO_ITEM'
export const TOGGLE_COMPLETED = 'TOGGLE_COMPLETED'

export const ADD_TODO_ITEM_NEW = 'ADD_TODO_ITEM_NEW'
export const DELETE_TODO_ITEM_NEW = 'DELETE_TODO_ITEM_NEW'
export const UPDATE_TODO_ITEM_NEW = 'UPDATE_TODO_ITEM_NEW'
export const TOGGLE_COMPLETED_NEW = 'TOGGLE_COMPLETED_NEW'

export const ADD_TODO_LIST = 'ADD_TODO_LIST'
export const DELETE_TODO_LIST = 'DELETE_TODO_LIST'
export const UPDATE_TODO_LIST = 'UPDATE_TODO_LIST'
export const SET_ACTIVE_TODO_LIST = 'SET_ACTIVE_TODO_LIST'

export const SHOW_ALL = 'SHOW_ALL'
export const SHOW_COMPLETED = 'SHOW_COMPLETED'
export const SHOW_INCOMPLETED = 'SHOW_INCOMPLETED'
export const REMOVE_COMPLETED = 'REMOVE_COMPLETED'

// Action for api
// -- data retrieval
export const REQUEST_TODOLISTS = 'REQUEST_TODOLISTS'
export const RECEIVE_TODOLISTS = 'RECEIVE_TODOLISTS'
export const INVALIDATE_TODOLISTS = 'INVALIDATE_TODOLISTS'
export const RESET_FETCHSTATE_ON_FAIL = 'RESET_FETCHSTATE_ON_FAIL'

// -- data update/delete/create
export const UPDATE_TODOLIST_REMOTE = 'UPDATE_TODOLIST'
export const DELETE_TODOLIST_REMOTE = 'DELETE_TODOLIST'
export const ADD_TODOLIST_REMOTE = 'ADD_TODOLIST_REMOTE'

// Action for Auth state
export const REQUEST_LOGIN = 'REQUEST_LOGIN'
export const RECEIVE_AUTH_TOKEN = 'RECEIVE_AUTH_TOKEN'
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const REQUEST_LOGOUT = 'REQUEST_LOGOUT'
export const REMOVE_AUTH_TOKEN = 'REMOVE_AUTH_TOKEN'
export const LOGOUT_FAILED = 'LOGOUT_FAILED'
